parameters:
#    bwf_articles.example.class: BWF\ArticlesBundle\Example

services:
#    bwf_articles.example:
#        class: %bwf_articles.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
